#!/bin/bash
alias get_idf='. $HOME/esp/esp-idf/export.sh'
. $HOME/esp/esp-idf/export.sh
idf.py build
python -m esptool --chip esp32s3 -b 460800 --before default_reset --after hard_reset write_flash --flash_mode dio --flash_size 2MB --flash_freq 80m 0x0 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/hello_world.bin
idf.py -p /dev/ttyACM0 monitor
